# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Ruyi Ji's Home Page
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
url: "https://jiry17.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg

header:
  pages:
    - name: Home
      slug: index
    - name: Research
    - name: Activity

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: jiruyi910387714@pku.edu.cn
      link: mailto:jiruyi910387714@pku.edu.cn
  follow:
    - name: GitHub
      link: https://github.com/jiry17

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
